### ISSUE TITLE
Tutorial: different syntax highlighting for code and comments is needed

### ISSUE THREAD

**Issue by GegznaV** [mlr-org/mlr#2383]
In `mlr` tutorial web pages (e.g., https://mlr-org.github.io/mlr/articles/task.html), it would be less tiring and easier to follow R code in the code chunks, if there was a contrast between the code and the comments/results (e.g., if these elements were in different colors). Is it possible to have this feature?

**Comment by GegznaV** [comment]
It is interesting: lines of code, that start with a single `#` are highlighted differently than lines with several hash symbols (`##`, `###`). There are some examples:

![image](https://user-images.githubusercontent.com/12725868/42722052-fa7d622a-874d-11e8-9695-bd01135f45fe.png)
versus
![image](https://user-images.githubusercontent.com/12725868/42722077-431cf8ce-874e-11e8-8f22-fd566691c2b3.png)

Basing on this, wouldn't it be reasonable to have a guideline to use only one hash symbol for comments in articles of `mlr` tutorial? Different colors really makes it easier to read.

**Comment by pat-s** [comment]
Yes, you're right. We should change this. Most likely this can be found in more tutorial pages.

**Comment by pat-s** [comment]
Fixed in aafc7de61435b111b8d9c6a67ddb70b122e84bff.

**Comment by GegznaV** [comment]
I'm not sure if the issue hat to be closed as it was not solved. 

**The first** thing I suggest is adding more contrast in code highlighting, e.g., this CSS code:

```css
/* Syntax highlighting theme */

.fl      {color: #1514b5;}
.co      {color: #888888;}    /* comments */
.ch, .st {color: green;}      /* strings */
.dv, .ot {color: darkblue;}   /* numbers, logicals */
.sourceCode.r .op {color: #505050;}  /* operators */
.sourceCode.r .dt {color: #303030;}  /* function argument names,  #303030 - darkgray */
.sourceCode.r .kw, .fu, .cf, .sourceCode a:link {color:darkred;} /* function names */
```

in `pkgdown\extra.css` file to get more contrast in code highlighting, e.g.:


![image](https://user-images.githubusercontent.com/12725868/42885081-b5caa47c-8aa8-11e8-989d-0a68834f026e.png)

instead of 

![image](https://user-images.githubusercontent.com/12725868/42885157-ea357516-8aa8-11e8-8bc5-132f0399bb04.png)
 in [this](https://mlr-org.github.io/mlr/articles/functional_data.html) tutorial. And

![image](https://user-images.githubusercontent.com/12725868/42885791-9f49cb68-8aaa-11e8-9b83-9c549c0fa24c.png)

instead of 

![image](https://user-images.githubusercontent.com/12725868/42885842-c0011974-8aaa-11e8-91c7-ceaa4c35c7e2.png)

in function reference.

The new colors are not very intensive thus do not distract, but make the code more distinguishable from the results and the comments, especially in places like this one:

![image](https://user-images.githubusercontent.com/12725868/42886158-8570937e-8aab-11e8-8a04-c0ce2a715978.png)

versus

![image](https://user-images.githubusercontent.com/12725868/42886098-66887c4c-8aab-11e8-9191-4c597cf2fb01.png)
